services:
  - type: web
    name: orion-net
    runtime: python
    plan: free
    buildCommand: "pip install websockets cryptography"
    startCommand: "python orion-net.py"
    autoDeploy: true

    envVars:
      - key: HUB_URL
        value: wss://orion-core.onrender.com

      - key: MY_ROOM_NAME
        value: Project Orion

      - key: PORT
        value: 8765

      - key: ROOM_MOTD
        value: Welcome To Orion Network.

      - key: ROOM_PASSWORD
        value: ""   # empty = public room

      - key: MSG_HISTORY_SIZE
        value: 50

      - key: RENDER_EXTERNAL_URL
        sync: false   # auto-provided by Render at runtime